// import { Inter } from "next/font/google";
// import "./globals.css";
// import Sidebar from "@/components/sidebar";
// import SHOP from "@/app/Shop/page.jsx";

// const inter = Inter({
//   subsets: ["latin"],
//   weight: ["100","200","300","400","500","600","700","800","900"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} antialiased`}>
        
//         <div className="grid grid-cols-1 lg:grid-cols-12 h-screen">
//           <aside className="lg:col-span-3 overflow-y-auto bg-[#F5F5F5]">
//             <Sidebar />
//           </aside>
//         <div className=" lg:col-span-9  p-4 bg-[#F5F5F5]">
//           <main
//             id="main-scroll"
//             className="lg:col-span-9 overflow-y-auto h-screen flex justify-center lg:justify-start bg-white rounded-2xl"
//           >
//             <div className="w-full max-w-5xl lg:max-w-none">
//               <SHOP />
//             </div>
//           </main>
//           </div>
//         </div>

//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import SHOP from "@/app/Shop/page.jsx";
import MainBgWrapper from "@/components/MainBgWrapper";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        
        <div className="grid grid-cols-1 lg:grid-cols-12 h-screen bg-[#F5F5F5]">
          <aside className="lg:col-span-3 overflow-y-auto bg-[#F5F5F5]">
            <Sidebar />
          </aside>
          
          <div className=" lg:col-span-9  lg:rounded-2xl lg:fixed lg:right-0 lg:left-97 ">
          <div className="lg:col-span-9 m-4 lg:fixed lg:right-0 lg:left-97 bg-white rounded-2xl overflow-hidden">
  <MainBgWrapper>
    <main
      id="main-scroll"
      className="overflow-y-auto h-screen flex justify-center lg:justify-start"
    >
      <div className="w-full max-w-5xl lg:max-w-none">
        <SHOP />
      </div>
    </main>
  </MainBgWrapper>
</div>

          </div>

        </div>

      </body>
    </html>
  );
}
